### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by anton-johansson** [pietschy/gwt-pectin#47]
Hey!

I like the looks of this library, and wish to use it (or something similar) in our GWT-project(s). But by the looks of it, it doesn't seem to be maintained. Or am I wrong? I'm using GWT 2.7.

If this isn't maintained, do you know if there's any other similar library?

Thanks in advance!

**Comment by pietschy** [comment]
Hi @anton-johansson,

Sadly gwt-pectin isn't maintained anymore - I've been away from gwt for quite a while.  You might want to check out https://github.com/stephenh/tessell by @stephenh.

Cheers

**Comment by anton-johansson** [comment]
Allright, thanks for the answer. I'll look into tessell!
